### PR TITLE
Update existsFile and bump the version.

### PR DESCRIPTION
**Pull request by swanhtet1992**

### CODE REVIEW

**Comment by pietroppeter** [comment]
Thanks! Will tag the release now!

**Comment by pietroppeter** [comment]
had to fix CI but now it is tagged and released

**Comment by swanhtet1992** [comment]
> had to fix CI but now it is tagged and released

Yeah, I saw it failed and looked for what is needed to be fixed today. As I am not familiar with github workflow, couldn't help.

Thanks for a great library btw. I am learning Nim and your codes help a lot.

**Comment by pietroppeter** [comment]
> Thanks for a great library btw. I am learning Nim and your codes help a lot.

you are welcome! that is very nice to hear! This library is actually the first thing I did in nim so code might not be great and I have not worked a lot on this (it could definitely use some love...). Feel free to ask other stuff either here (discussions) or on discord or on nimib discussion (the project I am most involved) or nim forum...

> Yeah, I saw it failed and looked for what is needed to be fixed today. As I am not familiar with github workflow, couldn't help.

it was actually tricky, I clicked on the red X for the failed CI (still accessible from list of commits: https://github.com/pietroppeter/nimoji/commits/master) and there I clicked on details and arrived here: https://github.com/pietroppeter/nimoji/actions/runs/4157331624/jobs/7191757615
there I saw that there was a problem with the action I use to setup nim (https://github.com/jiro4989/setup-nim-action) so I just updated to a recent release (I actually just did that on nimib repo, https://github.com/pietroppeter/nimib/pull/169, so I was fresh on the matter...).
Also something that changed is that the I think the way the CI is shown changed on github (CI was added a few commits ago but the green/red check appears only from your commit).

**Pull request merged**
